name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Deploy when pushing to the 'main' branch. You can change this if needed.
  
jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment to run your job on

    steps:
      # Step 1: Check out your code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (necessary for wrangler and npm if your project has dependencies)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can change the version as needed

      # Step 3: Install dependencies (if your project requires them, such as packages from npm)
      - name: Install dependencies
        run: npm install

      # Step 4: Install wrangler CLI (Cloudflare's deployment tool)
      - name: Install wrangler
        run: npm install -g wrangler

      # Step 5: Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # Use your secret API token from GitHub secrets
        run: wrangler publish
